project:
  type: book

book:
  title: "EEB313: Quantitative Methods in R for Biology"
  author: "Vicki M. Zheng & Mete K. Yuksel"
  date: today
  chapters:
    - index.qmd
    - about-us.qmd
    - downloadingR.qmd
    - part: "Lectures"
      chapters:
      - lec00-rstudio.qmd
      - lec01-markdown-workflows.qmd
      - lec02-base-r.qmd
      - lec03-dataframes-dplyr.qmd
      - lec04-data-wrangling.qmd
      - lec05-data-visualization.qmd
      - lec06-exploratory-data-analysis.qmd
      - lec07-intro-to-stats.qmd
      - lec08-linear-models.qmd
    - part: "Assignments"
    - part: "Project"
      chapters:
      - projects.qmd
      - databases.qmd
  repo-url: https://github.com/EEB313/eeb313.github.io
  sidebar:
    search: true
    border: true

format:
  html:
    theme:
      light: [cosmo, format/_light.scss]
    code-copy: true
    code-fold: false
    code-overflow: wrap

